name: BWA-MEM2 Performance Benchmark

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  bwa-mem2-benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential zlib1g-dev libbz2-dev liblzma-dev wget art-nextgen-simulation-tools

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

# BWA-MEM2 and zlib₋* variants prep
#
      - name: Checkout bwa-mem2 w/ latest bioconda patches applied
        uses: actions/checkout@v4
        with:
          repository: "dslarm/bwa-mem2"
          ref: "sse2neon"
          submodules: true
          path: bwa-mem2

      - name: Compile bwa-mem2
        run: |
          cd bwa-mem2
          make -j$(nproc)

      - name: Checkout zlib-rs
        uses: actions/checkout@v4
        with:
          repository: "trifectatechfoundation/zlib-rs"
          path: zlib-rs

      - name: Compile zlib-rs C bindings
        run: |
          cd zlib-rs/libz-rs-sys-cdylib/
          cargo build --release --no-default-features --features "c-allocator,gz"
          ls -alh target/release/libz_rs.so && nm target/release/libz_rs.so | grep gz

      - name: Checkout zlib-ng
        uses: actions/checkout@v4
        with:
          repository: "zlib-ng/zlib-ng"
          path: zlib-ng

      - name: Compile zlib-ng
        run: |
          cd zlib-ng && ./configure
          make -j$(nproc)

# Bioinformatics
#
      - name: Download E. coli reference genome and rename it to ecoli.fa
        run: |
          cd bwa-mem2
          wget ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/005/845/GCF_000005845.2_ASM584v2/GCF_000005845.2_ASM584v2_genomic.fna.gz
          gunzip GCF_000005845.2_ASM584v2_genomic.fna.gz && mv GCF_000005845.2_ASM584v2_genomic.fna ecoli.fa

      - name: Index reference genome with bwa-mem2
        run: |
          cd bwa-mem2
          time ./bwa-mem2 index ecoli.fa

      - name: Simulate some e.coli reads with a fixed seed (666)
        run: |
          cd bwa-mem2
          art_illumina -ss HS25 -i ecoli.fa -rs 666 -l 100 -f 1 -o ecoli_art_illumina_simlated_reads

#      - name: Download E. coli sample reads
#        run: |
#          wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR258/000/SRR2584863/SRR2584863_1.fastq.gz
#          wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR258/000/SRR2584863/SRR2584863_2.fastq.gz

      - name: Align reads with bwa-mem2
        run: |
          cd bwa-mem2
          ./bwa-mem2 mem ecoli.fa ecoli_art_illumina_simlated_reads.fq > alignment.sam

      - name: Run benchmarks w/ codspeed.io
        uses: CodSpeedHQ/action@v3
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: |
            cd bwa-mem2
            ./bwa-mem2 mem ecoli.fa ecoli_art_illumina_simlated_reads.fq > alignment.sam

#      - name: Convert SAM to BAM and sort
#        run: |
#          sudo apt-get install -y samtools
#          samtools view -Sb bwa-mem2-perf/alignment.sam | samtools sort -o alignment.sorted.bam

#      - name: Index BAM file
#        run: |
#          samtools index alignment.sorted.bam
